stages:
  - install monitoring
  - install ingress
  - prepare namespace

image:
  name: bitnami/kubectl
  entrypoint: [""]

variables:
  NAMESPACE_development: dev
  NAMESPACE_production: prod

.prepare_kubectl:
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  tags:
    - docker

install_monitoring:
  stage: install monitoring
  image:
    name: alpine/helm
    entrypoint: [""]
  before_script:
    - export KUBECONFIG=$KUBECONFIG
  script:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - |
      if helm ls --namespace monitoring | grep -q kube-prometheus-stack; then
        echo "Release 'kube-prometheus-stack' already exists. Skipping installation."
      else
        helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
      fi
  tags:
    - docker

install_grafana_ingress:
  stage: install ingress
  extends: .prepare_kubectl
  script:
    - kubectl apply -f manifests/

prepare_namespace:dev:
  stage: prepare namespace
  extends: .prepare_kubectl
  script:
    - |
      if ! kubectl get ns "${NAMESPACE_development}" > /dev/null 2>&1; then
          kubectl create ns "${NAMESPACE_development}"
        else
          echo "Namespace ${NAMESPACE_development} already exists, skipping creation."
        fi
    - |
      if kubectl get secret yandex-registry -n "${NAMESPACE_development}" >/dev/null 2>&1; then
        echo "Secret 'yandex-registry' already exist. Skipping step."
      else
        kubectl create secret docker-registry yandex-registry -n "${NAMESPACE_development}" \
          --docker-server="${CI_REGISTRY}/${CI_REGISTRY_ID}" \
          --docker-username="${CI_REGISTRY_USER}" \
          --docker-password="${CI_REGISTRY_PASSWORD}"
        echo "Registry has been installed."
      fi

prepare_namespace:prod:
  stage: prepare namespace
  extends: .prepare_kubectl
  script:
    - |
      if ! kubectl get ns "${NAMESPACE_production}" > /dev/null 2>&1; then
          kubectl create ns "${NAMESPACE_production}"
        else
          echo "Namespace ${NAMESPACE_production} already exists, skipping creation."
        fi
    - |
      if kubectl get secret yandex-registry -n "${NAMESPACE_production}" >/dev/null 2>&1; then
        echo "Secret 'yandex-registry' already exist. Skipping step."
      else
        kubectl create secret docker-registry yandex-registry -n "${NAMESPACE_production}" \
          --docker-server="${CI_REGISTRY}/${CI_REGISTRY_ID}" \
          --docker-username="${CI_REGISTRY_USER}" \
          --docker-password="${CI_REGISTRY_PASSWORD}"
        echo "Registry has been installed."
      fi      