apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
    requests.cpu: "500m"        
    requests.memory: "600Mi"   
    limits.cpu: "600m"          
    limits.memory: "700Mi" 